type Query {
  groups: [Group!]!
  users: [User!]!
}

type User {
  id: ID!
  first_name: String
  last_name: String
  groups: [Group!]!
  full_name: String
}

type Group {
  id: ID!
  name: String
  users: [User!]!
}