type Query {
  meals: [Meal!]!
  meal(id: ID!): Meal!
  categories: [Category!]!
  category(id: ID!): Category!
}

type Category {
  id: ID!
  name: String
  meals: [Meal!]!
}

type Meal {
  id: ID!
  name: String
  price: Float
  quantity: Int
  category: Category
}

type Mutation {
  createCategory(input: CreateCategoryInput!): Category!
  updateCategory(id: ID!, input: UpdateCategoryInput!): Category!
  createMeal(input: CreateMealInput!): Meal!
  updateMeal(id: ID!, input: UpdateMealInput!): Meal!
}

input CreateCategoryInput {
  name: String!
}

input UpdateCategoryInput {
  name: String
}

input CreateMealInput {
  name: String!
  price: Float!
  quantity: Int!
  category_id: ID!
}

input UpdateMealInput {
  name: String
  price: Float
  quantity: Int
  category_id: ID
}